### ISSUE TITLE
ansible 2 support

### ISSUE THREAD

**Issue by vanloswang** [OnApp/provisioner#71] opened 2016-09-26 03:06 UTC
deployed without docker, and the version of ansible is as following:
```bash
# ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
worker.py is not work due to api compability.
```bash
# python -u ./worker.py                                     
Traceback (most recent call last):
  File "./worker.py", line 1, in <module>
    from lib import ansible_helper
  File "/root/provisioner-master/lib/ansible_helper.py", line 1, in <module>
    import ansible.runner
ImportError: No module named runner
```
refer to http://docs.ansible.com/ansible/developing_api.html#python-api-2-0.

**Comment by vpetersson** [comment] 2016-09-26 07:18
Yup. Known issue. Duplicate of #16.

Migrating to Docker 2 requires a fair amount of effort. It's on the road map, but I don't know when I'll get around to it.

**Closed by vpetersson** 2016-09-26 07:18 UTC
